### ISSUE TITLE
Limit who can write snips

### ISSUE THREAD

**Issue by rugwirobaker** [robherley/snips.sh#43]
### What is the feature or enhancement?

If I'm self-hosting my own instance I'd like to somehow limit who can write snips to it.

**Comment by robherley** [comment]
Love the idea, want to toss around some ways we can achieve this:

1. Do we want this to be a configuration file (think like a `known_hosts` but for users) where the allowed fingerprints are stored on disk?
2. A new attribute in the DB (e.g.  `public_keys` table). But how would this be controlled by the admin? (e.g. command line args to the image, manually editing sqlite)

I'm leaning more towards (1) since having it in the DB may be awkward to setup. The amount of configuration options for snips are getting large, could warrant some kind of toml/yaml support for config too.

**Comment by robherley** [comment]
Here's a PR for the `authorized_keys` approach, I think that makes the most sense given the nature of the program 😄 
- https://github.com/robherley/snips.sh/pull/47

You should totally be able to use `~/.ssh/authorized_keys` too, users can configure it how they want, I left some info in the docs (like getting other user's public keys from `https://github.com/<username>.keys`)

Lemme know what y'all think 👍

**Comment by robherley** [comment]
@xabru 

> Using a configuration file in TOML or YAML format is a great idea and would be the next step to consider

Totally agree! The list of environment variables is getting quite long, I do like the idea of a snips config file to make it a bit easier. May roll with YAML because I'm personally not the biggest fan of TOML 😅 I'll take another look at [viper](https://github.com/spf13/viper) but might be super overkill for this use case.

> including the corresponding binaries in the releases section would be beneficial

I'm 50/50 on adding the binaries. In a perfect world, they'd be statically linked and set to go. But since we need libtensorflow dynamically linked for guessing the language, it can be a bit confusing with just the binary release, which is why I opted to use container images. I do have some (possibly bad) ideas to get around that, may open a discussion it.

**Comment by robherley** [comment]
With https://github.com/robherley/snips.sh/pull/47 this is now possible!
